folio-org/okapi

okapi-common/src/main/java/org/folio/okapi/common/ErrorType.java

* make documentation show up in context tooltips in IDEs
* let documentation appear in automatically produced API documentation

move documentation into javadoc comments

---

pom.xml

change maven repo from maven.indexdata.com to repository.folio.org

update distributionManagement in POM to point to FOLIO Nexus repository

---

.editorconfig
doc/bulkload.pl
doc/gh-133.sh
doc/load-aws.sh
okapi-common/src/main/java/org/folio/okapi/common/XOkapiHeaders.java
okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

Use .editorconfig configuration and apply consistent whitespace

FOLIO-351 EditorConfig

---

doc/guide.md

Adding documentation on how to send metrics to a remote grahpite 

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/service/impl/PostgresHandle.java

And leave out the postgres_url was completelby bogus and probably
may have originiated from some jDBC documentation.

Pass host and port to PostgresQL client

---

doc/guide.md

https://issues.folio.org/browse/FOLIO-475

FOLIO-475 clone github using https, not ssh

---

doc/guide.md

Update the responses in doc/guide.md

FOLIO-398 tidy 4

---

doc/guide.md
doc/guide.md.new
okapi-core/src/main/java/org/folio/okapi/bean/PermissionList.java

Review recent additions.
Update the responses in doc/guide.md

FOLIO-398 tidy 5

---

dist/hazelcast.xml
dist/okapi.conf
dist/okapi.env
dist/okapi.sh

FOLIO-351 tidy 1

---

doc/guide.md
doc/security.md

Reviewed the re-oragnised Guide.
Followed all examples.

OKAPI-286 tidy 1

---

doc/guide.md

OKAPI-286 tidy 2

---

okapi-core/src/main/java/org/folio/okapi/bean/ModuleInterface.java
okapi-core/src/main/java/org/folio/okapi/service/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/test/java/okapi/bean/ModuleInterfaceTest.java

The effect is that just one of them have to satisfy (OR).

Allow blank separated versions in requires

---

okapi-core/src/main/java/org/folio/okapi/service/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleId.java
okapi-core/src/test/java/okapi/ModuleTenantsTest.java

That is the module ID without version may be given and the latest
version (according to semver) is picked.

install: enable module is possible with product only OKAPI-395

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/test/java/okapi/ModuleTenantsTest.java

The install/upgrade may be performed with simulate=false or not
specifying simulate at all (since simulate=false is the default).

Install/upgrade without simulate OKAPI-399

---

okapi-core/src/test/java/okapi/ModuleTenantsTest.java

This tests introducing a new (sub) module which provides a new
interface major that nobody uses.. It will not be picked
in upgrade as expected. Secondly, another test which introduces
a new module that is capable of using it - and both will be upgraded.

More Unit Tests for upgrade OKAPI-350 work

---

okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java

In particular many calls to moduleManager.get are removed and
ModuleDescriptor from-to are passed around rather than module IDs.

Reduce and simplify in TenantManager

---

okapi-core/src/main/java/org/folio/okapi/pull/PullManager.java

Using up to 10 concurrent HTTP clients for fetching. This is close to
an optimal value.

Optimize pull operation OKAPI-403

---

okapi-core/src/test/java/okapi/DockerTest.java
okapi-core/src/test/java/okapi/ModuleTest.java
okapi-core/src/test/java/okapi/bean/BeanTest.java

Use module IDs with full semVer in tests

---

okapi-core/src/test/java/okapi/DockerTest.java
okapi-core/src/test/java/okapi/ModuleTest.java

No routingEntries in tests

---

okapi-core/src/test/java/okapi/ModuleTest.java

Do not use tenantInterface property in tests

---

okapi-core/src/main/java/org/folio/okapi/bean/ModuleDescriptor.java
okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
okapi-core/src/main/raml/ModuleDescriptor.json
okapi-core/src/test/java/okapi/ModuleTest.java

They are part of routing entries for handlers/filters now.

Remove support for modulePermissions in MD  OKAPI-411

---

okapi-core/src/test/java/okapi/MainClusterTest.java

It's getting extreme this time.

Further test coverage of MainCluster OKAPI-432

---

doc/guide.md

Enable link to
doc/guide.md#chunked

FOLIO-866 link docs

---

Jenkinsfile
NEWS.md
doc/guide.md

Verify the examples.
Update the response listings

OKAPI-436 review guide examples 1

---

Jenkinsfile
NEWS.md
doc/guide.md
doc/md2toc
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java

FOLIO-398 tidy 9

---

NEWS.md
doc/securing.md

FOLIO-398 tidy 10

---

NEWS.md
doc/securing.md
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java

FOLIO-398 tidy 11

---

doc/securing.md

Extract relevant fenced code blocks. Added syntax highlighting marker “script”.

FOLIO-462 perl one liner

---

doc/securing.md

OKAPI-462 perl one-liner 2

---

NEWS.md

FOLIO-398 tidy 13

---

NEWS.md
doc/guide.md
okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

FOLIO-398 tidy 14

---

okapi-core/src/main/java/org/folio/okapi/bean/InterfaceDescriptor.java
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/web/InternalModule.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/okapi/ModuleTest.java

/_/proxy/tenants/{tenant_id}/interfaces
and
/_/proxy/tenants/{tenant_id}/interfaces/{interface_id}

Support limit by interface type for two services OKAPI-496

---

NEWS.md
doc/md2toc
okapi-core/src/test/java/okapi/ModuleTest.java

FOLIO-398 tidy 15

---

okapi-core/src/main/java/org/folio/okapi/discovery/DiscoveryManager.java

This problem was caused by 39c598e42ff772455cb0907db390a7263c1b04d4

Fix result for a couple of async calls in discovery OKAPI-519

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

FOLIO-398 tidy 16

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
okapi-core/src/test/java/okapi/ModuleTest.java
okapi-test-auth-module/src/main/java/org/folio/okapi/auth/Auth.java

Fix missing X-Okapi-Permissions header, sanitize request headers better

Okapi 550 permheaders

---

okapi-core/src/main/java/org/folio/okapi/web/InternalModule.java

Rather than (null) which is a bit confusing.

Version service returns 0.0.0 when unknown OKAPI-555

---

NEWS.md
doc/index.md

Review and catalog Okapi docs

---

doc/index.md
doc/module-requirements.md

Skeletal draft of document specifying requirements for an Okapi module

---

NEWS.md

FOLIO-398 tidy 18

---

okapi-core/src/main/java/org/folio/okapi/service/impl/MongoUtil.java
pom.xml

Unfortunately that involves changing the code which handles
replace/add a document for Mongo.

Upgrade to Vert.x 3.5.1 OKAPI-602

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/test/java/okapi/ModuleTenantsTest.java
okapi-test-module/src/main/java/org/folio/okapi/sample/MainVerticle.java
okapi-test-module/src/test/java/SampleModuleTest.java

The disable now takes a diferent path; otherwise exactly the same
as first 1.1 attempt.

Version 1.1 of _tenant interface OKAPI-603

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java
okapi-core/src/test/java/okapi/ModuleTest.java
okapi-test-auth-module/src/main/java/org/folio/okapi/auth/Auth.java

Added a test case, and fixed a bug in the post-filter test.

Fix Okapi-617: Return OK code from handler, not post-filter.

---

doc/securing.md

Update example module versions. Current ones are all okay.

OKAPI-613 update securing doc 3

---

okapi-common/src/main/java/org/folio/okapi/common/Messages.java
okapi-common/src/main/java/org/folio/okapi/common/OkapiClient.java
okapi-common/src/test/java/org/folio/okapi/common/MessagesTest.java
okapi-common/src/test/resources/infra-messages/Messages_en.properties
okapi-core/src/main/java/org/folio/okapi/MainDeploy.java
okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/deployment/DeploymentManager.java
okapi-core/src/main/java/org/folio/okapi/discovery/DiscoveryManager.java
okapi-core/src/main/java/org/folio/okapi/env/EnvManager.java
okapi-core/src/main/java/org/folio/okapi/pull/PullManager.java
okapi-core/src/main/java/org/folio/okapi/service/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/service/impl/TenantStoreMongo.java
okapi-core/src/main/java/org/folio/okapi/service/impl/TenantStorePostgres.java
okapi-core/src/main/java/org/folio/okapi/util/DockerModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/util/LockedStringMap.java
okapi-core/src/main/java/org/folio/okapi/util/ProcessModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java
okapi-core/src/main/java/org/folio/okapi/web/InternalModule.java
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/okapi/DockerTest.java

add language support for all messages to user from _okapi-core_ and _okapi-common_. As for now only the ones that were visible in code as hard-coded strings

Okapi-620-language-support

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

OKAPI-627: Duplicated Okapi filter header

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

OKAPI-635: Return Auth filter error without relying on pre/post filter

---

okapi-core/src/main/raml/HealthDescriptor.json
okapi-core/src/main/raml/ModuleDescriptor.json
okapi-core/src/main/raml/ModuleList.json
okapi-core/src/main/raml/NodeDescriptor.json
okapi-core/src/main/raml/PullDescriptor.json
okapi-core/src/main/raml/RoutingEntry.json
okapi-core/src/main/raml/UiModuleDescriptor.json

Some typos and a couple of readability tweaks.

OKAPI-241 tidy JSON schema descriptions

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
pom.xml

Had to deal with a regression in 3.5.4
https://github.com/eclipse-vertx/vert.x/issues/2653

Upgrade to Vert.x 3.5.4 OKAPI-573

---

doc/guide.md
okapi-common/src/main/java/org/folio/okapi/common/XOkapiHeaders.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/okapi/ModuleTest.java
okapi-core/src/test/java/okapi/ProxyTest.java

FOLIO-398 tidy 24

---

okapi-core/src/test/java/okapi/DockerTest.java

Do not use the Messages in a test!

Fix Docker test hangs OKAPI-689

---

okapi-core/src/main/java/org/folio/okapi/util/DockerModuleHandle.java
okapi-core/src/main/resources/infra-messages/Messages_en.properties

Fix null ptr occurring when no EXPOSE is in Dockerfile.
Report properly, when no EXPOSE is present in Dockerfileb

Fix Docker create container fails with null error OKAPI-686

---

doc/securing.md

Needed for "log in" step to work.

Include active indicator set to true during create superuser

---

okapi-core/src/main/java/org/folio/okapi/bean/ModuleDescriptor.java
okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/MultiTenantTest.java

Use type=headers for auth testing check

---

doc/guide.md

Use proper MD for internal module in guide where..

---

okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java

Add permissionSet `okapi.proxy.pull.modules.post` to `okapi.modules`

---

doc-zh/README.md
doc-zh/guide.md

guide.md --translate `/doc/guide.md` to Chinese。
README.MD -- just a explanation doc

add guid.md Chinese version

---

NEWS.md
doc/guide.md
okapi-core/src/main/java/org/folio/okapi/util/TcpPortWaiting.java
okapi-core/src/main/raml/DeploymentDescriptor.json
okapi-core/src/main/raml/InterfaceDescriptor.json
okapi-core/src/main/raml/ModuleDescriptor.json
okapi-core/src/main/raml/RoutingEntry.json
okapi-core/src/main/raml/okapi.raml

Fix minor text typos, consistent JSON property descriptions, and minor whitespace.

FOLIO-398 tidy 26

---

okapi-core/src/main/java/org/folio/okapi/util/AsyncLock.java

Just increase the waiting time for the lock.

Fix timer calls terminated for connection refused OKAPI-734

---

okapi-core/src/main/java/org/folio/okapi/MainDeploy.java
okapi-core/src/main/resources/infra-messages/Messages_en.properties

Move the 'print help' in a method and use it also as default when no
command is given.

Create printUsage function

---

okapi-core/src/main/java/org/folio/okapi/managers/DeploymentManager.java
okapi-core/src/main/java/org/folio/okapi/managers/DiscoveryManager.java

Avoid calling /_/deployment/modules from discovery manager entirely
and use event bus instead. For undeploy also use event bus. Although
not necessary for this to work, it's same style.

Fix cannot restart Okapi when secured OKAPI-737

---

doc/guide.md

[OKAPI-747](https://issues.folio.org/browse/OKAPI-747)

Update guide to document database initialization behavior.

---

doc/guide.md

and mention the load{Sample,Reference} parameters

Add curl example to illustrate tenant loading

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

This partially reverts OKAPI-773

Missing permissions POSTed to permissions module OKAPI-819

---

doc/index.md

Updated index.md with minor changes.

Updated index.md

---

okapi-core/src/main/java/org/folio/okapi/bean/InterfaceDescriptor.java
okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-core/src/test/java/org/folio/okapi/bean/ModuleInterfaceTest.java

See [FOLIO-2603](https://issues.folio.org/browse/FOLIO-2603): ensure compatibility between Okapi 3.0 and mod-perms/mod-authtoken (BTW The JIRA has changed to [OKAPI-851](https://issues.folio.org/browse/OKAPI-851))

FOLIO-2603 (BTW JIRA has changed to OKAPI-851)

---

doc/internal-modules.md

Updated internal-modules.md with the missing full stops

Updated internal-modules.md

---

okapi-core/src/main/java/org/folio/okapi/MainCluster.java
okapi-core/src/main/java/org/folio/okapi/MainDeploy.java

OKAPI-857: Okapi crashes on vertx-cache dir when changing user 'okapi'

---

dist/okapi.conf
dist/okapi.sh

Set an Okapi specific name for vertx.cacheDirBase

OKAPI-857: Configure vertx.cacheDirBase

---

okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml

This fixes this warning:
`WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.`

Add Multi-Release true to fix warning OKAPI-885

---

okapi-common/src/test/java/org/folio/okapi/common/OkapiClientTest.java
okapi-common/src/test/java/org/folio/okapi/common/PauseResumeTest.java
okapi-core/src/main/java/org/folio/okapi/managers/DiscoveryManager.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/PullManager.java
okapi-core/src/test/java/org/folio/okapi/DockerTest.java
okapi-core/src/test/java/org/folio/okapi/EnvTest.java
okapi-core/src/test/java/org/folio/okapi/HealthCheckTest.java
okapi-core/src/test/java/org/folio/okapi/MainDeployTest.java
okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/MultiTenantTest.java
okapi-core/src/test/java/org/folio/okapi/OkapiPerformance.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-core/src/test/java/org/folio/okapi/PullTest.java
okapi-core/src/test/java/org/folio/okapi/TenantRATest.java
pom.xml

Also netty to 4.1.52.Final. There are code changes due to the
methods that have been removed from HttpClient.

Update to Vert.x 4.0.0 Beta 2 OKAPI-889

---

okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java

This "issue" was introduced in OKAPI-899.

Fix unit test fails on system wo Docker OKAPI-918

---

okapi-core/src/main/java/org/folio/okapi/service/impl/ProcessModuleHandle.java

Race condition in ProcessHandle.stop .. Avoid initiating shutdown if it's already in progress (or already done).

Okapi 919 illegal state exception

---

.gitignore

As somebody is guilty of often using that as logfile name.

Ignore out files

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/test/java/org/folio/okapi/InstallTest.java

Bad spelling will be squashed :-)

Mark successfully completed module upgrades as done OKAPI-926

---

dist/okapi.conf
dist/okapi.sh

Add support for dockerRegistries property in dist okapi.conf.

---

okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/org/folio/okapi/InstallTest.java

Ongoing completed jobs are skipped when deleting all jobs.
Deleting single ingoing job results in error.

Add delete of install job and all jobs OKAPI-942

---

dist/okapi.conf
dist/okapi.sh
doc/guide.md
okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java

[] is zero registries and disables pull requests.
[{}] is unauthenticated DockerHub.

OKAPI-945: Document dockerRegistries [] and [ {} ]

---

okapi-common/src/test/java/org/folio/okapi/common/OkapiClientTest.java
okapi-common/src/test/java/org/folio/okapi/common/PauseResumeTest.java
okapi-core/src/main/java/org/folio/okapi/managers/DiscoveryManager.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/PullManager.java
okapi-core/src/test/java/org/folio/okapi/DockerTest.java
okapi-core/src/test/java/org/folio/okapi/EnvTest.java
okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/MultiTenantTest.java
okapi-core/src/test/java/org/folio/okapi/PerformanceTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-test-module/src/test/java/SampleModuleTest.java
pom.xml

Update from Vert.x 4.0.0CR1 to CR2. There are breaking changes again..
https://github.com/eclipse-vertx/vert.x/commit/d58e82561ba8b040f99d2aea2bae21bcb5aab597

Update to Vert.x 4.0.0.CR2 OKAPI-955

---

dist/hazelcast.xml

From:
https://github.com/hazelcast/hazelcast/blob/4.0.z/hazelcast/src/main/resources/hazelcast-default.xml

Update to default Hazelcast version 4.0 OKAPI-956

---

doc/guide.md

Point to raml1.0 with FOLIO-2908 updates and update the guide a bit.

Folio 2908 updates

---

doc/unwanted-modules.md

This is based on hints from @wafschneider gave me yesterday in a Slack conversation. Hopefully it should make it possible for me to do Actual Work without my system going into paging frenzy.

New document, "Disabling and undeploying unwanted FOLIO modules"

---

okapi-core/src/test/java/org/folio/okapi/ModuleTest.java

A minor refactor to this, otherwise, old test.

Default for RestAssured log().ifValidationFails()

---

okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/bean/RoutingEntry.java
okapi-core/src/main/java/org/folio/okapi/managers/DeploymentManager.java
okapi-core/src/main/java/org/folio/okapi/managers/DiscoveryManager.java
okapi-core/src/main/java/org/folio/okapi/managers/EnvManager.java
okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/PullManager.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/service/impl/MongoUtil.java
okapi-core/src/main/java/org/folio/okapi/service/impl/PostgresQuery.java
okapi-core/src/main/java/org/folio/okapi/service/impl/ProcessModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/service/impl/Storage.java
okapi-core/src/main/java/org/folio/okapi/service/impl/TenantStoreMongo.java
okapi-core/src/main/java/org/folio/okapi/service/impl/TenantStorePostgres.java
okapi-core/src/main/java/org/folio/okapi/util/AsyncMapFactory.java
okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/main/java/org/folio/okapi/util/EventBusChecker.java
okapi-core/src/main/java/org/folio/okapi/util/LockedStringMap.java
okapi-core/src/main/java/org/folio/okapi/util/LockedTypedMap1.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleCache.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java
okapi-core/src/main/java/org/folio/okapi/util/TcpPortWaiting.java
okapi-core/src/main/java/org/folio/okapi/util/TokenCache.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java
okapi-core/src/test/java/org/folio/okapi/service/impl/ProcessModuleHandleTest.java
okapi-core/src/test/java/org/folio/okapi/util/LockedStringMapTest.java

Use Collections.singletonList for one arg. Use GenericCompositeFuture
instead of CompositeFuture. Many other minor changes.
Event `moduleUpdate` code removed as this is no longer in use.

Refactoring; use GenericCompositeFuture

---

okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java

Docker does not return JSON. It returns lines of JSON objects.
We just consider the first one which is all we need.

Fix exception on docker pull OKAPI-978

---

okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/test/java/org/folio/okapi/testutil/UtilityClassTester.java
okapi-core/src/test/java/org/folio/okapi/util/DepResolutionTest.java
okapi-core/src/test/java/org/folio/okapi/util/ModuleUtilTest.java

Steal UtilityClassTester from RMB.

Fix modules require does not consider optional deps OKAPI-987

---

dist/okapi.sh
doc/guide.md
okapi-core/src/main/java/org/folio/okapi/ConfNames.java

As requested by Adam on #1095.

Inconsistent conf names deploy.waitIterations + deploy_waitIterations

---

okapi-common/pom.xml
okapi-common/src/main/java/org/folio/okapi/common/ErrorTypeException.java
okapi-common/src/main/java/org/folio/okapi/common/ExtendedAsyncResult.java
okapi-common/src/main/java/org/folio/okapi/common/OkapiClient.java
okapi-common/src/main/java/org/folio/okapi/common/OkapiToken.java
okapi-common/src/test/java/org/folio/okapi/common/ExtendedAsyncResultTest.java
okapi-common/src/test/java/org/folio/okapi/common/OkapiClientTest.java
pom.xml

The new ErrorTypeException parallels the ExtendedAsyncResult Failure
for use in a Future.

OKAPI-1004: OkapiClient futurisation

---

okapi-core/src/main/java/org/folio/okapi/managers/TimerManager.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

Fix module upgrade disables timer OKAPI-1006

---

okapi-core/src/main/java/org/folio/okapi/bean/RoutingEntry.java
okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/raml/RoutingEntry.json
okapi-core/src/test/java/org/folio/okapi/MultiTenantTest.java
okapi-core/src/test/java/org/folio/okapi/bean/RoutingEntryTest.java

Approach:
"permissionsRequiredTenant": []

OKAPI-917: GET /_/version with valid token, no permission needed

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java

Please see https://issues.folio.org/browse/OKAPI-1016. The most meaningful change is to pass x-okapi-tenant header to mod-login-saml even for preflight. The stub handler generated by RMB checks that header all the time.

OKAPI-1016 Support saml preflight

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/CorsHelper.java

Please see https://issues.folio.org/browse/OKAPI-1015. Basically Okapi 4.8.0 will time out when sending /saml/login request. I spent quite bit time debugging the issue, and found the workaround as shown in this PR. I am not sure why the old way breaks though. It would be great if someone can take a look and explain it. Thanks.

OKAPI-1015 Fix saml login call timeout

---

okapi-common/src/test/java/org/folio/okapi/common/OkapiClientTest.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/org/folio/okapi/InstallTest.java

Increased timeout for okapi-common's OkapiClient test.. which involves a DNS lookup that may not fail within 5 seconds (increasing to 10 seconds).

Supply module id for some tenant errors OKAPI-1034

---

NEWS.md
okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml
okapi-testing/pom.xml
pom.xml

Release okapi 4.9.0 OKAPI-1032

---

okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/main/java/org/folio/okapi/util/TenantInstallOptions.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java
okapi-core/src/test/java/org/folio/okapi/util/DepResolutionTest.java

https://issues.folio.org/browse/OKAPI-1043

okapi reinstall OKAPI-1043

---

pom.xml

Fixes for running this on Apple M1

---

okapi-core/src/test/java/org/folio/okapi/service/impl/PostgresQueryTest.java
pom.xml

https://issues.folio.org/browse/OKAPI-1044

Upgrade to Vert.x 4.2.1 OKAPI-1044

---

okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml
okapi-testing/pom.xml
pom.xml

https://issues.folio.org/browse/OKAPI-1055

Automatic modules OKAPI-1055

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/test/java/org/folio/okapi/managers/ProxyServiceTest.java

If Okapi filters out strings that contain `${` it prevents any MDC lookup in the modules that haven't upgraded to log4j >= 2.17.0 and mitigates the log4j issue (CVE-2021-45105).
No modules need to be updated to log4j 2.17.0 if Okapi filters out invalid values that triggers the denial-of-service bug.
`${` is the default prefix for MDC lookups and used in FOLIO: https://github.com/apache/logging-log4j2/blob/rel/2.13.3/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/StrSubstitutor.java#L146-L151
MDC is used for these values:
* tenant id
* request id
* module id
* user id
A valid tenant id cannot contain `${`: https://github.com/folio-org/okapi/blob/v4.11.0/okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java#L739
A valid request id cannot contain `${`: …

OKAPI-1058: Reject MDC lookups mitigating log4j vuln (CVE-2021-45105)

---

debian/rules

https://issues.folio.org/browse/FOLIO-3371
The build process can be tested "by hand" by doing `fakeroot debian/rules build` .

Set JAVA_HOME when building deb package FOLIO-3371

---

okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/managers/PullManager.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleVersionFilter.java
okapi-core/src/main/java/org/folio/okapi/util/TenantInstallOptions.java
okapi-core/src/test/java/org/folio/okapi/util/ModuleUtilTest.java
okapi-core/src/test/java/org/folio/okapi/util/ModuleVersionFilterTest.java

This is a follow-up to OKAPI-1065. While this is more lines of code,
the logic is now all encapsulated in one class, which makes it clearer
how this works and easier to maintain.

Create class for snapshot filter handling OKAPI-1065

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java

Log elapsed time when calling tenant operation.
https://issues.folio.org/browse/OKAPI-1072

Log info of module activation OKAPI-1072

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java

Follow up.. Which fixes mix of nano and milliseconds !!

Fix timing calculation OKAPI-1072

---

okapi-core/src/main/java/org/folio/okapi/managers/DeploymentManager.java

Good to double-check environment passed to processes.

Log launch descriptor upon deployment

---

okapi-core/src/main/java/org/folio/okapi/util/EventBusChecker.java

Eventbus check: increase timeout

---

okapi-common/src/main/java/org/folio/okapi/common/SemVer.java
okapi-common/src/test/java/org/folio/okapi/common/SemVerTest.java

Switch to Long for SemVer component.
https://issues.folio.org/browse/OKAPI-1091

Fix exception SemVer with 4000001006 OKAPI-1091

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/ConfNames.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java
okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java

https://issues.folio.org/browse/OKAPI-1146

Fix various log wait issues OKAPI-1146

---

okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/DockerTest.java

This fixes issue with orphaned mod-users containers which occurred when running in test DockerTest#deployBadListeningPort .
Other cosmetic changes too.

Wait for containers to be closed and removed OKAPI-1140
