CONTRIBUTING.md
doc/guide.md

Synchronise copies of doc "CONTRIBUTING.md" and "folio-org.github.io/community/contrib-code.md".
Apply some consistent Markdown style.

Synchronise copies of contribution guide

---

okapi-core/src/main/java/org/folio/okapi/util/ProcessModuleHandle.java

The mode, is thus Redirect.PIPE for stderr.. We'll close it if the
spawn of module succeeds.

Okapi exec - save stderr so we can display error msg OKAPI-222

---

okapi-core/src/main/java/org/folio/okapi/web/TenantWebService.java

The Tenant API as it currently exists requires an X-Okapi-Tenant header to inform it which tenant to initialize.

Added X-Okapi-Tenant header to calls made to TenantAPI

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/bean/ModuleDescriptor.java
okapi-core/src/main/java/org/folio/okapi/bean/Permission.java
okapi-core/src/main/raml/ModuleDescriptor.json
okapi-core/src/main/raml/Permission.json
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/okapi/ModuleTest.java

Adds permission sets to the ModuleDescriptor. Those are not yet used for anything. Should be 100% backwards compatible.

Okapi 267 permsets

---

doc/guide.md
doc/security.md
okapi-core/src/test/java/okapi/ModuleTest.java
okapi-test-auth-module/src/main/java/org/folio/okapi/auth/Auth.java
okapi-test-auth-module/src/main/java/org/folio/okapi/auth/MainVerticle.java
okapi-test-auth-module/testdata/login.sh

Stripes expects logins to happen on the `/authn/login` interface, but the test/demo module in Okapi uses `/login`.  With this change, it is possible to use _Okapi-test-auth-module_ as an *authentication* source (but not an *authorization* source) for Stripes.  (Note that authorization can be bypassed in Stripes by using the `hasAllPerms: true` in the `config` dictionary of _stripes.config.js_.

OKAPI-342: Replace /login with /authn/login

---

doc/guide.md

Updated the curl responses.
Was considering removing the Okapi version number from the
Trace headers, because that might make the docs appear to
be out-of-date.
However, decided not to, as it makes future doc updates
more difficult.

FOLIO-398 tidy 8 update responses

---

okapi-common/src/main/java/org/folio/okapi/common/XOkapiHeaders.java
okapi-core/src/test/java/okapi/ModuleTest.java
okapi-test-auth-module/src/main/java/org/folio/okapi/auth/Auth.java

No changes needed in Okapi itself, only in test auth module, ModuleTest, and XOkapiHeaders.

Pass X-Okapi-User-Id around

---

okapi-core/src/main/java/org/folio/okapi/service/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleId.java
okapi-core/src/main/java/org/folio/okapi/util/SemVer.java
okapi-core/src/main/java/org/folio/okapi/web/InternalModule.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/okapi/PullTest.java
okapi-core/src/test/java/okapi/util/ModuleIdTest.java
okapi-core/src/test/java/okapi/util/SemVerTest.java

There are three new parameters for /_/proxy/modules: filter, orderBy
and order. Filter is module ID prefix - possibly only with leading
module name with none or partial version. The orderBy can only have
single value "id" at this point (module ID). Parameter order is
"asc" or "desc". If parameter orderBy is omitted no particular
sorting takes place.

Allow sorting and filter for module listing

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

The message "No tenantId, defaulting to okapi.supertenant" occurs a lot
in normal operation so it is hereby changed to debug level.

Make one log message debug rather than info

---

okapi-core/src/test/java/okapi/ModuleTest.java
okapi-core/src/test/java/okapi/bean/BeanTest.java

Property handlers should be used instead. Part of OKAPI-289 work

Update tests to not use routingEntries in provides

---

doc/guide.md

Use a element for internal doc links
The span works for Jekyll sites, but not via GitHub render.

FOLIO-866 link docs 2

---

okapi-core/src/main/java/org/folio/okapi/MainCluster.java

Ensure that property vertx.logger-delegate-factory-class-name is
set before we get a logger from LoggerFactory first time.

Fix strange logformat OKAPI-453

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java
okapi-core/src/test/java/okapi/ModuleTest.java

Only X-Okapi-Trace and -Tenant-Perms-Result saved when enabling
module for tenant (including install).

Fix install module results in huge number of headers OKAPI-466

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

by including the module ID in the 500 error.

Extend error information for two other proxy cases

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
okapi-core/src/test/java/okapi/ModuleTest.java

Just clear it after routing entries are resolved.

Fix X-Okapi-Module-ID is passed to callee OKAPI-474

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

Case 1: Internal requests that fails. Case 2: type headers that
returns failure (<200 or >=300).

Stop timer for two cases OKAPI-508

---

okapi-core/src/test/java/okapi/ProcessModuleHandleTest.java

Just wait longer time for the spawned process to start listening
on the port.

Fix unit test ProcessModuleHandleTest fails on Java9 OKAPI-539

---

NEWS.md
doc/guide.md
doc/md2toc

Allow underscore in generated ToC links
Match behaviour of GitHub and Jekyll rendering.
See notes at [OKAPI-568](https://issues.folio.org/browse/OKAPI-568)

OKAPI-568 md2toc allow underscore

---

okapi-core/pom.xml

Update postgresql-embedded from 2.4 to 2.9. This updates PostgreSQL from 9.6.3 to 9.6.8 fixing these security vulnerabilities:
CVE-2017-7546 empty password accepted
CVE-2017-7547 pg_user_mappings view discloses passwords
CVE-2017-7548 lo_put() function ignores ACLs
CVE-2017-12172 Start scripts permit to modify root-owned files
CVE-2017-15098 Memory disclosure in JSON functions
CVE-2017-15099 INSERT ... ON CONFLICT DO UPDATE fails to enforce SELECT privileges
CVE-2018-1053 pg_upgrade creates file of sensitive metadata under prevailing umask
CVE-2018-1058 Uncontrolled search path element
See list with details: https://www.postgresql.org/support/security/

OKAPI-569: Security update PostgreSQL 9.6.8, postgresql-embedded 2.9

---

okapi-core/src/main/java/org/folio/okapi/discovery/DiscoveryManager.java
okapi-core/src/main/java/org/folio/okapi/web/InternalModule.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/okapi/ModuleTenantsTest.java

Allow delete /discovery/modules/{serviceId} . This is simpler
than the full: /_/discovery/modules/{serviceId}/{instanceId}

Discovery delete with serviceId only OKAPI-577

---

okapi-core/src/main/java/org/folio/okapi/service/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/web/InternalModule.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/okapi/ModuleTenantsTest.java

This in fact changes the schema of that response, but since only "id"
was ever used, it is safe to change that to ModuleDescriptor list.

Extend /_/proxy/tenants/<t>/modules with full parameter OKAPI-588

---

doc/securing.md

Removed the documented workaround to re-enable for permissions OKAPI-388 which was fixed in okapi-2.3.1
Used the DeploymentDescriptor.json files provided by each module.

OKAPI-613 update securing doc

---

doc/securing.md

Explain deployment descriptors sed.
Enable the three modules in any order, but before mod-authtoken.

OKAPI-613 update securing doc 2

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java
okapi-core/src/test/java/okapi/ModuleTest.java

Fix in okapi-634 was not enough. Noticed a few API test errors in our environment. Heads-up, I will merge this once build is green to unblock API test failures in our env. Thanks.

OKAPI-635: Return Auth filter error to caller without relying on pre/post filter

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

Just use req.uri() rather than absoluteURI() which throws exception.

Fix OKAPI-643 Queries with double quotes crash

---

NEWS.md
doc/guide.md

Example URL: https://folio.example.com/okapi

OKAPI-653: Document that X-Okapi-Url may end with a path

---

okapi-core/src/main/java/org/folio/okapi/util/AsyncLocalmap.java
okapi-core/src/main/java/org/folio/okapi/util/LockedStringMap.java
okapi-core/src/test/java/okapi/util/LockedStringMapTest.java

This is achived by using the built-in AsyncMap.keys whith appeared in
Vert.x 3.5.0 rather than emulating it as. The problem with emulating the
keys-method was that we could often have collisions when modifying it.

Optimize shared map usage OKAPI-664

---

okapi-core/src/main/java/org/folio/okapi/util/LockedStringMap.java

In releases before 2.18 _keys was used to book keep all keys
for a map... Now in 2.18 and later, this should be ignored.

Ignore _keys from map from older Okapi OKAPI-667

---

dist/okapi.conf
dist/okapi.sh

In order for okapi deployment persistence to work, -Dnodename must be set when running in cluster mode.   Add configurable 'nodename' option to okapi.conf OR set as `hostname` when cluster mode is specified.

add -Dnodename as configurable option. Set a default in cluster mode

---

okapi-core/src/main/java/org/folio/okapi/service/ProxyService.java

This partly reverts the work of OKAPI-632 because that puts HTTP
response headers in HTTP headers and messes up the communication.

Avoid passing response headers to request headers OKAPI-671

---

okapi-core/pom.xml
okapi-core/src/main/raml/okapi.raml

Also had to update to the current latest raml-tester 0.9.1 which
partially supports RAML 1.0. The RAML was even fixed in a few places
where it was incorrect.

Update RAML to version 1.0 OKAPI-680

---

dist/hazelcast.xml

Update default hazelcast config to v3.11 compatible version that can be included in downstream distributions like https://github.com/folio-org/okapi-debian or used as a reference.

FOLIO-1612 update default hazelcast config to v3.11 compatible version

---

okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/test/java/okapi/ModuleTenantsTest.java

Since the problem with unknmown modules IDs is with POSTed
content rather than the URL 400 instead of 404 is returned.
Also all missing modules are reported (not just the first one).

Install: report 400 for modules not found OKAPI-614

---

doc/guide.md

Correct typo in guide.

---

okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java
okapi-core/src/test/java/org/folio/okapi/MultiTenantTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-test-auth-module/src/main/java/org/folio/okapi/auth/Auth.java
okapi-test-auth-module/src/test/java/AuthModuleTest.java

This includes slight change of behavior of the auth module as well
as a unit test for an Edge module that takes no special headers and
calls authn/login to get a token for further processing.

First part of Edge module work

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java

A small log change so we can see the response time for the full request path and parameters.

Adjust RES log to show request parameters

---

okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java

The fix is simple: optimize interface checks - that's methods
DepResolution.checkAllDependencies and DepResolution.checkDependencies

Fix deleting MD from Okapi causes Vert.x warning OKAPI-750

---

okapi-core/src/main/java/org/folio/okapi/util/AsyncLock.java

Supply a timeout less than 60 seconds for getLockWithTimeout to
avoid the warnings to be shown. The call is just repeated instead.

Prevent Vertx thread block warnings OKAPI-759

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java

It happened always betwen modules, but just not for the last
response.

Sanitize response headers OKAPI-764

---

README.md
okapi-core/Dockerfile

Uses the updated base docker image folioci/alpine-jre-openjdk8:latest
This has more recent Alpine Linux and more recent Java 8. See some notes at OKAPI-786 and FOLIO-2367.
Regarding testing of this change:
Since the merge of pull/865 ("OKAPI-321 domain sockets for docker") the default 'mvn clean install' does not build on macOS. So to test, i have done the following:
git checkout aac952e # which is just prior to that merge
edit okapi-core/Dockerfile
mvn clean install
cd okapi-core
docker build -f Dockerfile  -t test-okapi-docker .
docker run -d test-okapi-docker dev
docker exec -it `<CONTAINER ID>` bash
`# do some basic curl actions`
exit
docker logs `<CONTAINER ID>`

OKAPI-786 Use new base docker image

---

okapi-core/src/main/java/org/folio/okapi/service/impl/ProcessModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java

The setting is renamed to deploy.waitIterations since the property is called waitIterations in deployment descriptor.. The configuration (if set) takes precedence over everything else.

Fluagen okapi 789 max conn iteration config

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java

This is passed in request in some cases (which it shouldn't).

For caching, ignore X-Cache header

---

okapi-common/src/main/java/org/folio/okapi/common/OkapiClient.java
okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/bean/ModuleDescriptor.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/PullManager.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/service/impl/Storage.java
okapi-core/src/main/java/org/folio/okapi/service/impl/TenantStoreMongo.java
okapi-core/src/main/java/org/folio/okapi/service/impl/TenantStorePostgres.java
okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/main/java/org/folio/okapi/util/LockedTypedMap2.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-test-auth-module/src/test/java/AuthModuleTest.java

This PR improves coverage in general for install. It ensures that the tenant module association is not happening until all modules have been completing tenant init and tenant permissions interface. Of course, if the modules do not implement these interfaces, they will not be considered. Also if a module is not running at all, of course, also that stops upgrading. There's no switch for this. This changes behavior for the better, so a desired breaking change = bug fix.
Out of scope of this issue:
We should extend the tenant interface with a rollback mechanism so that module can be notified to rollback if they have succeeded but another module has failed. 
Finally, we could do a pre-check tenant init which has no side effects but just let the module ack that it can do upgrade (without …

Okapi 773 switch discovery only if all succeeds

---

okapi-core/src/test/java/org/folio/okapi/ModuleTest.java

See OKAPI-826: PostgreSQL 10.11-3 Mac version does not exist on enterprisedb.com

Match PostgreSQL Mac version on enterprisedb.com

---

.editorconfig

If IDEA uses editorconfig it uses a contination indent to be same as
indent_size (2).. We want it to be 4. This setting is probably only
recognoized by IDEA.

For IntelliJ IDEA use continuation indent of 4

---

okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java

LANG=de_DE.UTF-8 mvn clean install
fails in DockerModuleHandleTest#testNoDockerAtPort()
because netty translates "Connection refused" to
"Verbindungsaufbau abgelehnt".
This fix changes the exception message and the test
to be more locale independent.

Remove locale dependency

---

okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml
pom.xml

Use BOM (bill of material) for
* Vert.x (obsoletes ${vertx-version})
* log4j
* junit
Move dependencies that depend on Vert.x version to root pom.xml and add upgrade notice.
These dependencies are managed by Vert.x BOM. Remove our hard-coded version and
use the version from BOM, resulting in a version upgrade:
* netty-transport-native-epoll (4.1.15.Final to 4.1.49.Final)
* jackson-core (2.10.1 to 2.10.2)
* jackson-databind (2.10.1 to 2.10.2)
Upgrade hazelcast versions to match Vert.x hazelcast version:
* hazelcast (3.12 -> 3.12.2)
* hazelcast-kubernetes (1.5 -> 1.5.1)

OKAPI-850: Dependency management (bom), Vert.x 4.0 deps

---

okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/bean/RoutingEntry.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/util/CorsHelper.java
okapi-core/src/main/raml/RoutingEntry.json
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

See [OKAPI-847](https://issues.folio.org/browse/OKAPI-847): Conditionally defer CORS handling to module when invoked via passthrough API

Allow delegate CORS to module

---

dist/okapi.sh

Collect all postgres_* variables, encode them as JSON, write them to
okapi-postgres.conf (at the writeable directory PID_DIR), and pass
the file via the -conf parameter.
Include postgres_server_pem only if defined (even if empty string).

OKAPI-858: okapi.sh should not put credentials into -D command line

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-core/src/test/java/org/folio/okapi/managers/ProxyServiceTest.java
okapi-test-module/src/test/java/SampleModuleTest.java

This should decrease the memory usage for upload and download for Okapi. The problem is fixed by switching from
https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClientRequest.html#write-io.vertx.core.buffer.Buffer-
to
https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClientRequest.html#write-io.vertx.core.buffer.Buffer-io.vertx.core.Handler-
The problem with the former is that, since it will not block it will pile up the request or response in memory.. Using the latter and pause the source from data until complete minimizes memory.
This PR has a test-case for okapi-test-module.. That is an end-to-end client + server to analyze the problem, which turned out to be useful.
2nd part is "just" the fix for Okapi and a similar test case .

OKAPI-866 OOM bulk upload

---

pom.xml

Updating Netty from 4.1.42.FINAL to 4.1.51.Final fixes
https://www.cvedetails.com/cve/CVE-2019-16869/
Updating Jackson databind from 2.9.9 to 2.10.2 fixes
https://www.cvedetails.com/cve/CVE-2019-14540/
https://www.cvedetails.com/cve/CVE-2019-16335/
https://www.cvedetails.com/cve/CVE-2019-16942/
https://www.cvedetails.com/cve/CVE-2019-16943/
https://www.cvedetails.com/cve/CVE-2019-17267/
The vulnerable versions are from vertx-stack-depchain 4.0.0-milestone4.
vertx-stack-depchain 4.0.0-milestone5 has fixed versions: https://github.com/vert-x3/vertx-dependencies/compare/4.0.0-milestone4...4.0.0-milestone5
But we cannot update to vertx-stack-depchain 4.0.0-milestone5 because of other bugs: https://issues.folio.org/browse/OKAPI-865
Therefore we need to manually overwrite the versions from …

OKAPI-873: Update Netty (CVE-2019-16869) and Jackson (CVE-2019-14540)

---

pom.xml

Goldenrod runs Okapi 2.40.
Okapi 3.* has been upgraded to use log4j 2.13.2:
https://issues.folio.org/browse/OKAPI-873
This is the backport of this upgrade to Okapi 2.40
to get these issues fixed in Goldenrod:
* https://issues.apache.org/jira/browse/LOG4J2-2809
see https://issues.folio.org/browse/OKAPI-873 for details
* https://nvd.nist.gov/vuln/detail/CVE-2020-9488
"Improper validation of certificate with host mismatch in
Apache Log4j SMTP appender." This may affect an implementer
if the sysop uses encrypted SMTP for logging.

OKAPI-877: Update log4j to 2.13.3 in okapi 2.40 (CVE-2020-9488)

---

.gitignore
dist/okapi.sh
doc/guide.md
okapi-core/pom.xml
okapi-core/src/main/java/org/folio/okapi/MainDeploy.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/util/MetricsHelper.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java
okapi-core/src/test/java/org/folio/okapi/MainDeployTest.java
okapi-core/src/test/java/org/folio/okapi/util/MetricsHelperTest.java
pom.xml

Please see [OKAPI-860](https://issues.folio.org/browse/OKAPI-860). Following meters (and tags) are defined and implemented for Okapi HTTP proxy calls. There is no error meter defined for server side because that is covered by server processingTime meter. The naming convention follows [Vert.x core tools metrics](https://vertx.io/docs/vertx-micrometer-metrics/java/#_vert_x_core_tools_metrics). Note, the dot in the name is converted to _ in InfluxDB automatically.
- org.folio.okapi.http.server.processingTime - metrics type is Micrometer Timer. Tags are below
- host - Okapi instance. An example value: ip-172-31-19-200.ec2.internal/172.31.19.200
- tenant - FOLIO tenant id. An example value: diku
- code - HTTP response code. An example value: 200
- method - HTTP request method. An example …

Okapi 860 metrics

---

Jenkinsfile
README.md
debian/control
okapi-core/Dockerfile
pom.xml

Tested building Okapi with JDK 11 and it seems fine. Since this PR changes the compile level to 11, we have to wait until Jenkins building environment is updated.

Okapi 879 jdk11

---

okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml
pom.xml

Log4j2Plugins.dat in a shaded jar file fails:
https://issues.apache.org/jira/browse/LOG4J2-673
Delete the file from the shaded fat jar.

OKAPI-883: Log4j2Plugins.dat in fat jar: Unrecognized format specifier

---

doc/guide.md
okapi-core/pom.xml
okapi-core/src/main/java/org/folio/okapi/bean/AnyDescriptor.java
okapi-core/src/main/java/org/folio/okapi/bean/EnvEntry.java
okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/util/VariableSubstitutor.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java
okapi-core/src/test/java/org/folio/okapi/util/VariableSubstitutorTest.java
okapi-test-module/Dockerfile
okapi-test-module/ModuleDescriptor.json
okapi-test-module/descriptors/ModuleDescriptor-dockerImage.json

Okapi passes environment variables like DB_PASSWORD=mysecret
to Docker to deploy a module. These variables should be
suppressed in the log. (OKAPI-882)
Okapi expands the %p and %c variables in the complete JSON.
It should expand %p in exec, cmdlineStart and dockerArgs only,
and expand %c in dockerArgs only. (OKAPI-884)
For dockerArgs introduce %% to allow literal %.

OKAPI-882, OKAPI-884: Password in log, variable expansion

---

Jenkinsfile

Set 'buildDeb= true' option in Jenkinsfile to automatically build .deb package for okapi releases.

Enable .deb packaging in the okapi pipeline

---

dist/okapi.sh

The okapi startup script, okapi.sh, needs to be updated to check for openJDK-11.   The version check itself also needs to be updated to reflect the different format that openJDK-11 outputs with 'java -version'   With openJDK-8,  the version would be reported as '1.8.x'.   With openJDK-11, the format has changed to '11.x.x'.

update java check for openjdk-11 in okapi startup script

---

okapi-common/pom.xml
okapi-common/src/main/java/org/folio/okapi/common/OkapiClient.java
okapi-common/src/test/java/org/folio/okapi/common/OkapiClientTest.java

This makes OkapiClient simpler and allows the code to be compatible with
both Vert.x 4 and Vert.x 3.9 series.

OkapiClient: use WebClient rather than HttpClient OKAPI-896

---

okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
pom.xml

Restore the missing `L` from `Location`, which doesn't actually matter
since the test for the `ocation` substring still succeeds, but this
looks nicer.

restore the missing L in Location

---

okapi-core/src/main/raml/DeploymentDescriptor.json
okapi-core/src/main/raml/DeploymentDescriptorList.json
okapi-core/src/main/raml/EnvEntry.json
okapi-core/src/main/raml/EnvEntryList.json
okapi-core/src/main/raml/HealthDescriptor.json
okapi-core/src/main/raml/HealthDescriptorList.json
okapi-core/src/main/raml/HealthStatus.json
okapi-core/src/main/raml/HealthStatusList.json
okapi-core/src/main/raml/InstallJob.json
okapi-core/src/main/raml/InstallJobList.json
okapi-core/src/main/raml/InterfaceDescriptor.json
okapi-core/src/main/raml/InterfaceList.json
okapi-core/src/main/raml/InterfaceReference.json
okapi-core/src/main/raml/LaunchDescriptor.json
okapi-core/src/main/raml/ModuleDescriptor.json
okapi-core/src/main/raml/ModuleList.json
okapi-core/src/main/raml/NodeDescriptor.json
okapi-core/src/main/raml/NodeDescriptorList.json
okapi-core/src/main/raml/Permission.json
okapi-core/src/main/raml/PullDescriptor.json
okapi-core/src/main/raml/RoutingEntry.json
okapi-core/src/main/raml/TenantDescriptor.json
okapi-core/src/main/raml/TenantList.json
okapi-core/src/main/raml/TenantModuleDescriptor.json
okapi-core/src/main/raml/TenantModuleDescriptorList.json
okapi-core/src/main/raml/UiModuleDescriptor.json

Refer to [OKAPI-914](https://issues.folio.org/browse/OKAPI-914).
Enables the use of stand-alone '[ajv](https://github.com/ajv-validator/ajv)' schema validator, as well as other tools.

OKAPI-914 Use "id" keyword in ModuleDescriptor JSON Schema

---

okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java

Avoid tampering with dockerArgs. The LaunchDescriptor must not
be modified by Docker Deployment.. The %p-things and other must be
preserved. If not the port is not subsituted upon restart.

Fix Okapi Docker deployment URL/port mismatch on restart OKAPI-915

---

okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

This did not reveal any issues but was done when working with MODPERMS-34. It also makes the module that is tested to not use timers where they are not needed (in ProxyTest that is).

Extend ProxyTest with more testing of tenantPermissions POST

---

pom.xml

Version 5.7.0 fixes version check for JUnit4.
https://junit.org/junit5/docs/5.7.0/release-notes/index.html#new-features-and-improvements-3

Upgrade junit-bom from 5.6.2 to 5.7.0 OKAPI-923

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java

instead of explicitly incorporating things like tenant and userId into the cache key we use the entire token in the request as part of the cache key since it includes this information. In doing so, we need to ensure that we don't allow cache keys w/ token=null. See [OKAPI-921](https://issues.folio.org/browse/OKAPI-921)
Additional context: [FOLIO-2839](https://issues.folio.org/browse/FOLIO-2839)

OKAPI-921 skip token cache if no request token is present

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java

Configuration property `dockerRegistries` includes list of registries
with authentication properties (as Docker uses them) and/or `registry` property. The latter to allow for pull on other repositories than DockerHub.

Docker pull with authenticated user OKAPI-912

---

okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/test/java/org/folio/okapi/util/DepResolutionTest.java

Fixes install does not honor dependencies OKAPI-925

---

dist/okapi.sh

No other way than passing a wealth of command-line arguments. This
is hereby done for the Debian package.

Fix Hazelcast Warnings (due to Java 9 or later) OKAPI-894

---

doc/guide.md
okapi-core/pom.xml
okapi-core/src/main/java/org/folio/okapi/MainDeploy.java
okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/util/MetricsHelper.java
okapi-core/src/test/java/org/folio/okapi/MainDeployTest.java
okapi-core/src/test/java/org/folio/okapi/util/MetricsHelperTest.java
pom.xml

Added metrics support for backend Prometheus (and JMX). Documentation is updated as below. I will create a follow up ticket to move some stuff to okapi-common, so RMB can use it directly.
Okapi uses Micrometer to managing metrics and reporting to backends. To enable it,
add Java parameter `-Dvertx.metrics.options.enabled=true` first.
More Java parameters are needed to config which backends to use
* `-DinfluxDbOptions='{"uri": "http://localhost:8086", "db":"okapi"}'` - Send metrics to InfluxDB
* `-DprometheusOptions='{"embeddedServerOptions": {"port": 9930}}'` - Expose `<server>:9930/metrics` for Prometheus
* `-DjmxMetricsOptions='{"domain": "org.folio.metrics"}'` - JMX
Another Java parameter can be used to filter metrics
* `-DmetricsPrefixFilter=org.folio` - Will only report metrics with …

Add more metrics backends (Prometheus and JMX) support

---

okapi-core/src/test/java/org/folio/okapi/managers/HealthManagerTest.java

Not 9130 which is the port that Okapi uses by default - including
the Debian package.

Make HealthManagerTest use port 9230 OKAPI-929

---

okapi-common/pom.xml
okapi-common/src/main/java/org/folio/okapi/common/MetricsUtil.java
okapi-common/src/test/java/org/folio/okapi/common/MetricsUtilTest.java
okapi-core/pom.xml
okapi-core/src/main/java/org/folio/okapi/MainDeploy.java
okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/util/MetricsHelper.java
okapi-core/src/test/java/org/folio/okapi/util/MetricsHelperTest.java

Moved some metrics code, for example supporting for different backends, to Okapi-common package, so RMB can use it without duplicating effort.

OKAPI-928: Move metrics to Okapi-common for sharing

---

okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java

Cannot use a lambda because Mockito does not support
matching a Supplier vararg when an Object vararg exists

OKAPI-903: Logging object reference rather than JSON

---

doc/guide.md

With Okapi 4.X it seems to be mandatory

add permissionsRequired to okapi-module-auth.json

---

dist/okapi.sh

* Do not add `dockerRegistries` property to okapi-runtime.conf if not defined
* Support deprecated `postgres_user` variable for `--initdb` operation

Fixes for dist okapi.sh (OKAPI-937)

---

doc/guide.md
doc/proposal-to-separate-interfaces.md

also verifying CI operation for [FOLIO-2855](https://issues.folio.org/browse/FOLIO-2855) to de-reference JSON Schemas before the generate-api-docs stage.

FOLIO-398: Fix minor text typos and punctuation

---

okapi-core/src/main/java/org/folio/okapi/util/LockedStringMap.java

Called from DiscoveryManager.shutdown. Not really seen because
the problem is shutting down anyway.

Fix NPE in LockedStringMap.clear

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/MainDeploy.java
okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/managers/DeploymentManager.java
okapi-core/src/main/java/org/folio/okapi/managers/DiscoveryManager.java
okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/PullManager.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleCache.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/org/folio/okapi/MainDeployTest.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-core/src/test/java/org/folio/okapi/util/ModuleCacheTest.java
okapi-core/src/test/java/org/folio/okapi/util/ModuleUtilTest.java
okapi-core/src/test/resources/install2.json
okapi-core/src/test/resources/modules2.json

OKAPI-916... More refactoring than at first sight, because the matching.. redirects.. auth caching.. metrics was all combined in one function. The ModuleCache is "unaware" of tenants, and is managed by TenantManager so that there's one ModuleCache per tenant. The redirect functionality is ugly and not in use.. We should consider removing it.
Running through all end points for Q2 modules, the number of match invocations is down from about 500k to 5k. That's ProxyTest.testManyModules.

Okapi 916 match path using hash

---

okapi-common/pom.xml
okapi-common/src/main/java/org/folio/okapi/common/GenericCompositeFuture.java
okapi-common/src/test/java/org/folio/okapi/common/GenericCompositeFutureTest.java

Coordinate a List<Future<T extends Future <?>>>, provides
all(List<T>), any(List<T>) and join(List<T>) that work like
CompositeFuture#all(List), CompositeFuture#any(List) and
CompositeFuture#join(List) but properly check the
generic type <T extends Future<?>>.
See https://github.com/eclipse-vertx/vert.x/pull/3595 why Vert.x doesn't have this.

OKAPI-943: GenericCompositeFuture

---

okapi-core/src/main/java/org/folio/okapi/service/impl/ProcessModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/util/TcpPortWaiting.java
okapi-core/src/test/java/org/folio/okapi/service/impl/DockerModuleHandleTest.java
okapi-core/src/test/java/org/folio/okapi/service/impl/ProcessModuleHandleTest.java
pom.xml

Made two small changes to get failed tests pass. For EC2, the connection refused message does not match perfectly. For mac, it turns out the NuProcess returns the sh pid but not the Java pid. So the NuProcess object is not null and is not running, the tryConnect loop does not capture this. Extending the timer wait time to let tryConnect succeed as a work around.
After updating Docker on my Mac, I start to see lots of Ryuk connection error. Updating testcontains version fixed that. There was an issue reported for testcontainer. See https://github.com/testcontainers/testcontainers-java/pull/3159

OKAPI-944 failed tests on mac and ec2

---

README.md

To qualify for the Open Source Project status under the
`Docker Open Source Policy` FOLIO as a publisher needs to
comply with the `Joint Marketing Programs` requirement:
"While the publisher retains the Open Source project status, the Publisher agrees to -
* Become a Docker public reference for press releases, blogs, webinars, etc
* Create joint blogs, webinars and other marketing content
* Create explicit links to their Docker Hub repos, with no ‘wrapping’ or hiding sources of their images
* Document that Docker Engine or Docker Desktop are required to run their whitelisted images
* Give Docker full attribution"
Okapi is the first pinned repository on https://github.com/folio-org
The Docker text has been copied from
https://dev.folio.org/download/artifacts/

Link Docker and Ubuntu repositories

---

dist/okapi.sh

How did that stray `$` get in there?

Fix typo in dist/okapi.sh

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

Fix for OKAPI-936 Request logging can send compressed data to the filter. Until now only the Content-Type was forwarded from request-response pipeline.. request-only, headers should NOT forward this as the response is thrown away.

Forward Content-Encoding header OKAPI-936

---

doc/guide.md

I think at this stage the old *Implementation* section is actively misleading.

Remove obsolete stub section from Okapi Guide

---

.gitignore
doc/guide.md
okapi-core/src/main/java/org/folio/okapi/bean/InterfaceDescriptor.java
okapi-core/src/main/java/org/folio/okapi/bean/ModuleInstance.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/org/folio/okapi/InstallTest.java
okapi-core/src/test/java/org/folio/okapi/managers/TenantManagerTest.java
okapi-core/src/test/java/org/folio/okapi/testutil/ModuleTenantInitAsync.java

PR for version 2.0 of _tenant interface. It will use the paths for POST, GET, DELETE as provided. Version 1 series are still supported and there should be no changes in behavior. So this is a pure extension as far as Okapi is concerned.
Should a Location be returned at runtime and yet the module descriptor only says 1.1 / 1.2 , Okapi issues an error. That is maintainer forgets https://github.com/folio-org/raml-module-builder/pull/815 .

OKAPI-875 async tenant init

---

debian/okapi.service

OKAPI-966. This change is required because of a change to the docker-ce Debian package.

Update Okapi systemd service configuration

---

dist/okapi.sh
doc/guide.md
okapi-common/src/main/java/org/folio/okapi/common/Config.java
okapi-common/src/test/java/org/folio/okapi/common/ConfigTest.java
okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-test-auth-module/src/main/java/org/folio/okapi/auth/MainVerticle.java
okapi-test-header-module/src/main/java/org/folio/okapi/header/MainVerticle.java
okapi-test-module/src/main/java/org/folio/okapi/sample/MainVerticle.java

"http.port" is the command-line option name that all RMB based
modules support:
https://github.com/folio-org/raml-module-builder#command-line-options
For consistency Okapi should also support this.
The guide.md should show "http.port" because most modules
are RMB based and support only this form.

Support both "http.port" and "port" property variables

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java

Fix this brain-damage - due to previous behavior when we were caching modules as a whole (for all tenants).. In that case we could ignore when a module was disabled.. In the current design.. of course all changes to modules enabled for a tenant needs to be published to all okapi instances.

Publish reload-modules also when disabling module OKAPI-967

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/util/ProxyContext.java

Please see https://issues.folio.org/browse/OKAPI-959. Tested the change with InfluxDB and I can see `org_folio_okapi_http_server_processingTime` metric fields `module` and `url` are populated now.

OKAPI-959 restore missing metrics code

---

okapi-core/src/main/java/org/folio/okapi/bean/Permission.java
okapi-core/src/main/java/org/folio/okapi/bean/PermissionList.java
okapi-core/src/main/java/org/folio/okapi/bean/PermissionListV1.java
okapi-core/src/main/java/org/folio/okapi/bean/PermissionListV2.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/raml/Permission.json
okapi-core/src/test/java/org/folio/okapi/InstallTest.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

Implement changes to facilitate static permission migration.  For details, see https://wiki.folio.org/display/DD/Migration+of+Static+Permissions+Upon+Upgrade?src=contextnavpagetreemode
Also see:  https://issues.folio.org/browse/OKAPI-947
* Add a `renamedFrom` field to the module descriptor permission schema indicating a permission's previously used name(s)
* Adjust the payload for the _tenantPermissions call to include:
* `moduleIdFrom` - the name/version of the module currently in use/being upgraded from (if applicable)
* `permsFrom` - the list of permissions defined by the version of the module currently in use (if applicable)
* `permsTo` - renamed from `perms` for clarity. 
* `moduleIdTo` - renamed from `moduleId` for clarity.
* When upgrading mod-permissions, call the …

OKAPI-947 - Updates for static permissions migration

---

pom.xml

Upgrade testcontainers from 1.15.0 to 1.15.1 to make it work with latest docker
Release notes: https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.1
Without this upgrade unit tests that use testcontainers no longer work.

OKAPI-970: testcontainers 1.15.1 needed for latest docker

---

README.md
okapi-core/src/test/java/org/folio/okapi/service/impl/PostgresHandleTest.java

FOLIO switches from embedded-postgresql to testcontainers.org that use
Docker PostgreSQL containers for tests in RMB based modules, RMB and Okapi:
FOLIO-1845
It no longer makes sense to skip tests if Docker is not available.
Tests should fail by default if we cannot run all tests so that any Docker
malfunction on the developer machine and on CI is noticed immediately. It
is misleading if such tests are skipped by default, see comments on OKAPI-970.
DockerModuleHandleTest, ModuleTest and PostgresHandleTest require Docker.
This pull request removes
@Testcontainers(disabledWithoutDocker = true)
PostgresHandleTest. (The other two files already fail on missing Docker).
And it adjust README.
If there really is a need to run only those tests that don't require
Docker please create a new Jira for …

OKAPI-971: Fail unit tests if docker is not available

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/bean/Permission.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/raml/Permission.json
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

* Update documentation for [OKAPI-947](https://issues.folio.org/browse/OKAPI-947).  
* Change the `renamedFrom` property to be called `replaces` in the Permission schema.
* Bump `_tenantPermissions` to `2.0` since `permissionSets.permission.replaces` isn't supported by mod-permissions (until MODPERMS-115 is complete).
See also:
* [MODPERMS-115](https://issues.folio.org/browse/MODPERMS-115)
* https://wiki.folio.org/display/DD/Migration+of+Static+Permissions+Upon+Upgrade

OKAPI-947 Update documentation, renamedFrom -> replaces, and bump _tenantpermissions version

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/TcpPortWaiting.java

Use WebClient on module host+port to see if module is alive, rather
than just TCP socket agsinst host and port. The latter is unreliable
in cases of Containers where exposed port is ready "immediately". This
in turn fixes Okapi startup with mod-permissions being called for
the purpose of upgrading the okapi module for a tenant.

Use HTTP check for module readiness in deployment OKAPI-984

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/main/java/org/folio/okapi/util/TenantInstallOptions.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

1. Removing module sends module with empty list via _tenantPermission so that permissions module may mark those permissions as no longer in use by the module.
2. Config option: `enable_system_auth` to control whether to call auth even if it's enabled. Highly insecure, so this is something that can not be controlled at runtime.
3. install parameter `invoke` is a string rather than a `boolean`. Values `true` and `false` honored as before. Other value is regular expression for controlling which modules to invoke.

Inform mod-permissions when module is disabled OKAPI-982

---

okapi-common/src/test/java/org/folio/okapi/common/GenericCompositeFutureTest.java
pom.xml

Update Vert.x from 4.0.0 to 4.0.2 fixing many bugs:
https://github.com/vert-x3/wiki/wiki/4.0.2-Release-Notes
Update Netty from 4.1.53 to 4.1.59 fixing a security issue (CVE-2021-21290):
https://github.com/netty/netty/security/advisories/GHSA-5mcr-gq6c-3hq2
Update micrometer and hazelcast dependencies.

OKAPI-986: Vert.x 4.0.2, Netty 4.1.59 (CVE-2021-21290)

---

okapi-core/src/main/java/org/folio/okapi/managers/DeploymentManager.java
okapi-core/src/main/java/org/folio/okapi/service/impl/DockerModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/service/impl/ProcessModuleHandle.java
okapi-core/src/main/java/org/folio/okapi/util/TcpPortWaiting.java

There were two problems: 1) incorrect default host passed
for checking container readiness; 2) not waiting enough time
by default (changed from 30 to 60).
This PR also makes a different wait-connect message so that
module ID and host:port is shown together.

Fix Docker deployment fails - part two OKAPI-988

---

okapi-core/src/main/java/org/folio/okapi/managers/DiscoveryManager.java

Increase to 1 hour. Blocks https://issues.folio.org/browse/FOLIO-3034
I'm going to merge as soon as one has approved. Just saying.

Fix Okapi discovery times out after 5 minutes OKAPI-992

---

PERSONAL_DATA_DISCLOSURE.md

Please see https://issues.folio.org/browse/OKAPI-960 Add personal data disclosure form 
Note:
- okapi-common logging uses `userId`
- `IP` is used in https://github.com/folio-org/okapi/blob/master/okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java#L584
2021-03-03
Add below item as personal data per core platform discussion
- User search queries

OKAPI-960 Add PERSONAL_DATA_DISCLOSURE form

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java

1. reload permissions when mod-permissions is being enabled (not upgraded)
2. reload permissions at end of install when mod-permissions is upgraded.
Previously permissions was reloaded at the end always.

Reload permissions immediately on enable (not upgrade) OKAPI-996

---

okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/util/CorsHelper.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

Please see https://issues.folio.org/browse/OKAPI-876. 
- Check CORS delegate just once to be efficient
- Allow preflight/OPTIONS to be delegated too

OKAPI-876 Simplify CORS delegate and support preflight too

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/util/CorsHelper.java

If a method always returns a succeeded Future containing the result
the Future is no needed and should be removed.
Unneccessary Future wrapping bloates the code.

Remove Future from return values

---

NEWS.md
okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml
pom.xml

Fixes only for 4.7 series.. in particular to get mod-login-saml working. also https://issues.folio.org/browse/OKAPI-1001 .. If Okapi is pinned for R1, this should be used.

4.7.3 NEWS

---

NEWS.md
okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml
okapi-testing/pom.xml
pom.xml

Release, because 4.8.1 didn't include proper cherry-picked commits.

Release 4 8 2

---

okapi-common/pom.xml
okapi-core/pom.xml
okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/service/ModuleStore.java
okapi-core/src/main/java/org/folio/okapi/service/impl/ModuleStoreMongo.java
okapi-core/src/main/java/org/folio/okapi/service/impl/ModuleStorePostgres.java
okapi-core/src/main/java/org/folio/okapi/service/impl/MongoUtil.java
okapi-core/src/main/java/org/folio/okapi/service/impl/PostgresQuery.java
okapi-core/src/main/java/org/folio/okapi/service/impl/PostgresTable.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
pom.xml

Connection timeout when PullManager writes > 14000 module descriptors
from folio-registry.dev.folio.org into PostgreSQL.
* Run Okapi with empty database
* curl -w '\n' -D - -X POST -H "Content-type: application/json" -d '{ "urls": ["https://folio-registry.dev.folio.org"] }' http://localhost:9130/_/proxy/pull/modules
Successfully inserts > 14000 module descriptors into PostgreSQL
```
17:43:01 [239139/proxy] [supertenant] [] [] INFO  PullManager          pull: 14313 MDs to insert
17:43:35 [239139/proxy] [supertenant] [] [] WARN  ProxyContext         Timeout
```
And some module descriptors are NOT written to the database.
This is the current implementation:
https://github.com/folio-org/okapi/blob/v4.8.2/okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java#L122-L131 …

OKAPI-1023: Pull module descriptors with bulk, fix connection timeout

---

okapi-core/pom.xml
okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/org/folio/okapi/managers/InternalModuleTest.java

/_/proxy/tenants/{tenant_id}/upgrade upgrades each module to the latest version
and therefore doesn't needs a body to list the version to upgrade to.
Steps to Reproduce:
* POST /_/proxy/tenants/{tenant_id}/upgrade with body
Expected Results:
Error message about the useless body.
Actual Results:
Upgrades to latest versions ignoring the version specified in the body.
Additional Information:
The documentation in
https://github.com/folio-org/okapi/blob/v4.8.2/okapi-core/src/main/raml/okapi.raml
correctly explains that no body is needed and it upgrades to the latest version.
(The wording can be improved, though.)
Okapi provides
* /_/proxy/tenants/{tenant_id}/install
* /_/proxy/tenants/{tenant_id}/upgrade
being misleading at first glance because one might assume that install is intended
for …

OKAPI-1025: /_/proxy/tenants/{tenant_id}/upgrade with body

---

okapi-core/src/test/java/org/folio/okapi/service/impl/MongoUtilTest.java
pom.xml

Upgrade
* Vert.x from 4.1.0 to 4.1.2. Most notable fix is the
"prepared statement ... already exists" issue:
https://github.com/eclipse-vertx/vertx-sql-client/pull/737
* hazelcast-aws from 3.3 to 3.4
* hazelcast-kubernetes from 2.2.1 to 2.2.3
MongoClient in Vertx 4.1.2 has more methods. To avoid adding them to FakeMongoClient in MongoUtilTest.java the Mockito spy method for abstract classes is used instead. This allows to delete all unused methods. Missing asyncAssertSuccess/asyncAssertFailure calls were added to ensure that the verification block is acutally been executed.

OKAPI-1027: Upgrade to Vert.x 4.1.2 (and hazelcast-aws/-kubernetes)

---

okapi-core/src/main/java/org/folio/okapi/util/CorsHelper.java

Add a Access-Control-Max-Age header to allow browsers to cache CORS responses.
This cache is per URL only, though.
Without this header Chromium has a default cache time of 5 seconds, Firefox has no cache.

OKAPI-1029: Cache CORS requests using Access-Control-Max-Age header

---

debian/preinst

package removal removes /var/lib/okapi but not the user okapi.
Therefore a reinstall needs to create the directory even if the user already exists.

OKAPI-1031: "apt-get install okapi" should recreate /var/lib/okapi

---

okapi-core/src/main/java/org/folio/okapi/bean/ModuleDescriptor.java
okapi-core/src/test/java/org/folio/okapi/bean/ModuleDescriptorTest.java
okapi-core/src/test/java/org/folio/okapi/util/ModuleUtilTest.java

Reduces boilerplate code in tests, see example in ModuleUtilTest.

Add ModuleDescriptor constructor with id

---

okapi-core/src/main/java/org/folio/okapi/MainVerticle.java
okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/main/java/org/folio/okapi/managers/ModuleManager.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/PullManager.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/java/org/folio/okapi/service/ModuleStore.java
okapi-core/src/main/java/org/folio/okapi/service/impl/ModuleStoreMongo.java
okapi-core/src/main/java/org/folio/okapi/service/impl/ModuleStoreNull.java
okapi-core/src/main/java/org/folio/okapi/service/impl/ModuleStorePostgres.java
okapi-core/src/main/java/org/folio/okapi/service/impl/Storage.java
okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/main/java/org/folio/okapi/util/ModuleUtil.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-core/src/test/java/org/folio/okapi/util/ModuleUtilTest.java

New service `/_/proxy/cleanup/modules?saveReleases=`N`&saveSnapshots=`M
where
N is the number of latest releases where snapshots are never considered obsolete
M is the number of latest snapshots that are never considered obsolete (preserved)
Remove method Future<Void> insert(ModuleDescriptor md) from
ModuleStore interface as it's no longer in use with OKAPI-1023
work.

Facility to remove obsolete modules OKAPI-1024

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/ConfNames.java
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/raml/okapi.raml
okapi-core/src/test/java/org/folio/okapi/ModuleTenantsTest.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

This, strickly speaking, a breaking change since the default
behavior has changed. But nothing, except reporting tools,
will be affected by this. Headers can be controlled with
config trace_headers.

Disable X-Okapi-Trace header by default OKAPI-1038

---

okapi-core/pom.xml
pom.xml

Bump cron-utils from 9.1.3 to 9.1.6.
Okapi doesn't use the `@Cron` annotation to validate untrusted Cron expressions and therefore is not affected by these security issues:
* CVE-2021-41269 https://nvd.nist.gov/vuln/detail/CVE-2021-41269 fixed in cron-utils >= 9.1.6
* CVE-2020-26238 https://nvd.nist.gov/vuln/detail/CVE-2020-26238 fixed in cron-utils >= 9.1.3
For details see https://securitylab.github.com/advisories/GHSL-2020-212-cron-utils-ssti/
Dependabot notice: https://github.com/folio-org/okapi/security/dependabot/pom.xml/com.cronutils:cron-utils/open

cron-utils 9.1.6

---

okapi-core/src/main/java/org/folio/okapi/MainDeploy.java
pom.xml

Upgrade Hazelcast from 4.0.2 to 4.2.2 which is
what Vert.x 4.2.1 is using anyway. And set logging
type to log4j2 (rather than log4j).

Hazelcast 4.2.2, logging log4j2 OKAPI-1048

---

dist/okapi.env

Fixes the log4j remote execution security issue (CVE-2021-44228).

OKAPI-1050: -Dlog4j2.formatMsgNoLookups=true for Debian/Ubuntu

---

okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml

okapi-common has multiple maven dependencies:
* log4j-api
* log4j-core
* vertx-core
* vertx-web
* vertx-web-client
* vertx-micrometer-metrics
* micrometer-registry-influx
* micrometer-registry-prometheus
* micrometer-registry-prometheus
* micrometer-registry-jmx
* cql-java
Most okapi-common users don't need all of them, this blows up the jar file.
A okapi-common user most likely already has the required dependencies in the own pom.xml file (and can easily add it if not).
Therefore all dependencies should be optional.

OKAPI-1052: okapi-common only optional maven dependencies

---

dist/okapi.env

This reverts commit 3bc30d8151dabeb9c90b555976906d796d375384.
The formatMsgNoLookups configuration is no longer needed
since we've upgraded to log4j 2.16.0.

OKAPI-1051: Revert "OKAPI-1050: -Dlog4j2.formatMsgNoLookups=true"

---

pom.xml

FOLIO is affected because Okapi and RMB use
https://github.com/folio-org/okapi/blob/v4.11.0/okapi-common/src/main/java/org/folio/okapi/common/logging/FolioLoggingContext.java
https://issues.folio.org/browse/OKAPI-1056
https://nvd.nist.gov/vuln/detail/CVE-2021-45105
https://logging.apache.org/log4j/2.x/security.html

OKAPI-1056: Log4j 2.17.0 fixing self-referential lookups

---

pom.xml

https://issues.folio.org/browse/OKAPI-1057
https://vertx.io/blog/eclipse-vert-x-4-2-2/
https://github.com/netty/netty/security/advisories/GHSA-wx5j-54mm-rqqq
https://nvd.nist.gov/vuln/detail/CVE-2021-43797

Vert.x 4.2.2, Netty 4.1.72.Final fixing header request smuggling

---

okapi-common/pom.xml
okapi-core/pom.xml
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java
okapi-core/src/test/java/org/folio/okapi/service/impl/PostgresHandleTest.java
okapi-test-auth-module/pom.xml
okapi-test-module/pom.xml
pom.xml

Update Vert.x from 4.2.2 to 4.2.3
Update log4j from 2.17.0 to 2.17.1
Update awaitility from 4.0.3 to 4.1.1
Update junit from 4.13.1 to 4.13.2
Update junit-bom from 5.7.1 to 5.8.2
Update assertj-core from 3.16.1 to 3.22.0
Update maven-resources-plugin from 3.0.1 to 3.2.0
Update git-commit-id-plugin from 2.2.1 to 4.9.10

OKAPI-1063: Bump dependencies: Vert.x 4.2.3, log4j 2.17.1, etc.

---

pom.xml

Update Vert.x from 4.2.4 to 4.2.5. This updates indirect dependencies
like netty from 4.1.73.Final to 4.1.74.Final.
https://github.com/vert-x3/wiki/wiki/4.2.5-Release-Notes

OKAPI-1074: Vert.x 4.2.5

---

okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/test/java/org/folio/okapi/util/DepResolutionTest.java

Change strategy on conflicts and upgrade if possible on
same product and then turn to disable.
The problem in this case is ui-inventory-es that is left
over from Juniper and no longer part of Kiwi, but not really
replaced or disabled. The new behavior is to disable modules
with conflicts (that are not explicitly installed).

Fix install fails migrating from Juniper to Kiwi OKAPI-1075

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java

The default case (parallel=1) was using the generic algorithm, but
that seems not to complete in reference builds.

Handle parallel=1 in sequence OKAPI-1077

---

okapi-core/src/test/java/org/folio/okapi/InstallTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

This PR tunes tests a bit so Okapi can complete its test with a relatively slow server.
The slow server being based on AMD A10 Micro-6700T.

Unit test fixes for slow server

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java

This property which should only be set to false for testing
purposes is now also checked when phase auth is called in proxy.

Property enable_system_auth checked for proxy calls

---

pom.xml

Update jackson-databind from 2.13.1 to 2.13.2.1 fixing https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Update Vert.x from 4.2.5 to 4.2.6.
Update log4j from 2.17.1 to 2.17.2.

OKAPI-1088: jackson-databind 2.13.2.1, Vert.x 4.2.6, log4j 2.17.2

---

README.md

A link to local files and another to generated documentation on
dev.folio.org.

Add links to RAML

---

pom.xml

This fixes a few bugs: https://github.com/vert-x3/wiki/wiki/4.2.7-Release-Notes
The explicit jackson-bom is no longer needed because
vertx-stack-depchain has been updated to latest jackson.

OKAPI-1094: Update Vert.x from 4.2.6 to 4.2.7

---

okapi-common/src/main/java/org/folio/okapi/common/HttpClientFactory.java
okapi-common/src/main/java/org/folio/okapi/common/WebClientFactory.java
okapi-common/src/test/java/org/folio/okapi/common/HttpClientFactoryTest.java

Provide a HttpClientFactory similar to WebClientFactory. They should share the same HttpClients.
Quote from https://vertx.io/docs/vertx-web-client/java/ :
> The HttpClient should be used when fine grained control over the HTTP requests/responses is necessary.
> The Web Client does not provide a WebSocket API, the Vert.x Core HttpClient should be used. It also does not handle cookies at the moment.
Adding support for HttpClient will cover all uses cases and allows for a smoother transition to these non-leaking factories.

OKAPI-1095: HttpClientFactory (with WebClientFactory)

---

NEWS.md
okapi-common/pom.xml
okapi-core/pom.xml
okapi-test-auth-module/pom.xml
okapi-test-header-module/pom.xml
okapi-test-module/pom.xml
okapi-testing/pom.xml
pom.xml

Set master to 5.0.0-SNAPSHOT to ensure this is "newer" than 4.14 release(s)
and because there are a few breaking changes already.

5.0.0-SNAPSHOT 4.14.0 NEWS

---

okapi-core/pom.xml
pom.xml

Bump org.glassfish:javax.el:3.0.1-b12 to org.glassfish:jakarta.el:3.0.4 fixing a bug in the Jakarta Expression Language implementation that enables invalid EL expressions to be evaluated as if they were valid: https://nvd.nist.gov/vuln/detail/CVE-2021-28170
Note that the artifact has been renamed from javax.el to jakarta.el: https://mvnrepository.com/artifact/org.glassfish/javax.el

OKAPI-1098: Fix Jakarta Expression Language validation (CVE-2021-28170)

---

okapi-core/pom.xml
okapi-core/src/test/java/org/folio/okapi/InstallTest.java
pom.xml

Upgrade vertx from 4.2.7 to 4.3.1.
Upgrade micrometer from 1.6.3 to 1.8.4.
Upgrade nuprocess from 2.0.2 to 2.0.3.
Upgrade several test dependencies.
In InstallTest rewrite tests so that they succeed regardless
whether the async install has completed or not. This is needed
for Vert.x 4.3.1.

OKAPI-1100: Vert.x 4.3.1, micrometer 1.8.4, nuprocess 2.0.3, test deps

---

debian/rules
dist/log4j2.properties

Since OKAPI-902 released with Okapi 4.12.1 the Debian Okapi package no longer logs to /var/log/folio/okapi/okapi.log but to STDOUT ending in /var/log/syslog.
The log entries look like this:
```
Jul 01 13:41:17 esx-243 okapi.sh[560237]: 13:41:17 [] [] [] [] INFO  ?                    834705/testb RES 200 33893us test-basic-1.0.0 http://localhost:9131/testb
```
And they are mixed with log messages from other processes.
Revert to okapi.log to avoid duplicate data in log lines and to have Okapi log separate from other logs.

OKAPI-1109: Log to /var/log/folio/okapi/okapi.log, not STDOUT, in Debian

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java

A regression of the OKAPI-1111 work. Bascially X-Okapi-Token
should not be passed when we call auth-filter as it may not be
for the same tenant as we invoke for (the whole purpose of calling
it, is to get a token).

Fix X-Okapi-Token wrongly passed OKAPI-1113

---

okapi-core/pom.xml
pom.xml

glassfish:javax.el has a Jakarta Expression Language validation vulnerability (CVE-2021-28170). We have fixed this with a workaround - https://issues.folio.org/browse/OKAPI-1098 - resulting in these dependencies:
```
[INFO] org.folio.okapi:okapi-core:jar:5.0.0-SNAPSHOT
[INFO] +- com.cronutils:cron-utils:jar:9.1.6:compile
[INFO] |  \- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] \- org.glassfish:jakarta.el:jar:3.0.4:compile
```
Now cron-utils has switched from javax.el to jakarta.el, our workaround is no longer needed.
Task: Bump cron-utils from 9.1.6 to 9.2.0. This automatically includes jakarta.el so that we can remove our explicit jakarta.el dependency.
This will result in these dependencies:
```
[INFO] org.folio.okapi:okapi-core:jar:5.0.0-SNAPSHOT
[INFO] \- …
```

OKAPI-1118: cron-utils 9.2.0, clean up javax.el/jakarta.el

---

pom.xml

Upgrade nuprocess from 2.0.3 to 2.0.5 to fix a Arbitrary Command Injection vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2022-39243

OKAPI-1122: nuprocess 2.0.5 fixing Arbitrary Command Injection

---

pom.xml

Upgrade Vertx from 4.3.3 to 4.3.4. This indirectly upgrades jackson-bom from 2.13.2.1 to 2.13.4 fixing a Denial of Service (DoS) vulnerabilities in jackson-databind: https://nvd.nist.gov/vuln/detail/CVE-2022-42003 , https://nvd.nist.gov/vuln/detail/CVE-2022-42004
Upgrade micrometer from 1.9.3 to 1.9.4.
Upgrade log4j from 2.17.2 to 2.19.0.
Upgrade several test dependencies.

OKAPI-1125: Vert.x 4.3.4, micrometer 1.9.4, log4j 2.19.0

---

doc/guide.md

And avoid mention what it does for old-style _tenant interface.

Stick to what purge does for install

---

okapi-core/src/main/java/org/folio/okapi/bean/PermissionList.java
okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/test/java/org/folio/okapi/ModuleTest.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

For _tenantPermissions 2.1, pass replaces property with modules that this replaces.
https://issues.folio.org/browse/OKAPI-1151

Pass replace property for permissions OKAPI-1151

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
okapi-core/src/main/raml/okapi.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 OKAPI-1166 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

doc/guide.md
okapi-core/src/main/java/org/folio/okapi/managers/InternalModule.java
okapi-core/src/test/java/org/folio/okapi/util/DepResolutionTest.java

Before this commit, modules could not really require the interface as it was not considered in dependency resolution (install).

okapi interface is a normal interface OKAPI-1199

---

okapi-core/src/main/java/org/folio/okapi/managers/ProxyService.java
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

The client will set that on its own based on the absolute URI.

Proxy: do not relay Host header OKAPI-1201

---

okapi-common/src/main/java/org/folio/okapi/common/refreshtoken/client/impl/LoginClient.java
okapi-common/src/main/java/org/folio/okapi/common/refreshtoken/client/impl/RefreshClient.java
okapi-common/src/test/java/org/folio/okapi/common/refreshtoken/client/impl/LoginClientTest.java
okapi-common/src/test/java/org/folio/okapi/common/refreshtoken/client/impl/RefreshClientTest.java

although this information is already part of value in X-Okapi-Token.
This is required as folio module sidecar requires X-Okapi-Tenant to be set.

refreshtoken client sets X-Okapi-Tenant

---

okapi-core/src/main/java/org/folio/okapi/util/DepResolution.java
okapi-core/src/test/java/org/folio/okapi/util/DepResolutionTest.java

https://folio-org.atlassian.net/browse/OKAPI-1209
The topological sort does not properly take into account when it's safe to disable a module and the dep check considers it's not safe to remove it, despite a "new" module offers the same interface The strategy is to allow "remaining" modules to be disabled in the end.

OKAPI-1209 fix install when replacing module

---

okapi-core/src/main/java/org/folio/okapi/managers/TenantManager.java
okapi-core/src/main/raml/TenantModuleDescriptor.json
okapi-core/src/main/resources/infra-messages/Messages_en.properties
okapi-core/src/test/java/org/folio/okapi/ProxyTest.java

https://folio-org.atlassian.net/browse/OKAPI-1210
Very often, the install has just enable all the way. If the action can be omitted, then the list of enabled modules for tenant can be straight up fed to install for, say, another tenant.

OKAPI-1210 default action is enable

---

okapi-core/src/main/java/org/folio/okapi/MainVerticle.java

On initdatabase failure we do not need stop the Verticle. It is stopped already because a failure is returned.

OKAPI-1200 fix ModuleTest.testInitdatabaseBadCredentials fails

---

okapi-common/src/main/java/org/folio/okapi/common/refreshtoken/client/impl/LoginClient.java
okapi-common/src/test/java/org/folio/okapi/common/refreshtoken/client/impl/LoginClientTest.java

https://vertx.io/docs/apidocs/io/vertx/ext/web/client/HttpResponse.html#bodyAsBuffer()
Weird that empty body should not be a buffer.

OKAPI-1211 fix NPE in refreshtoken client
